version: "3"
services:
    WebSphere:
        image: iaf-test-as-websphere
        restart: unless-stopped
        volumes:
          - type: bind
            source: ../../../test/src/test/testtool/
            target: /opt/frank/testtool-ext
        ports:
            - "80:9080"
            - "9443:9443"
            - "9043:9043"
        environment:
            - larva.adapter.execute
            - dtap.stage=LOC