version: '3.4'

services:
    samba:
      #image: stanback/alpine-samba
      build: ./samba
      restart: unless-stopped
      container_name: samba
      volumes:
        - samba-v:/srv/samba/shared
      ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139/tcp"
      command: --no-process-group
      networks:
        - waf-net
  
    kdc:
      build: ./kerberos
      restart: unless-stopped
      container_name: kerberos
      ports:
      - "88:88/udp"
      - "464:464"
      - "749:749"
      environment:
        KRB5_REALM: WEAREFRANK.NL
        KRB5_KDC: localhost
        KRB5_PASS: pass_123
      volumes:
      - krb5kdc:/var/lib/krb5kdc
      networks:
        - waf-net

    ftp-server:
      build: ./ftp
      restart: unless-stopped
      container_name: ftp
      ports:
        - "21:21"
        - "21000-21010:21000-21010"
        - "30000-30099:30000-30099"
      environment:
        ADDRESS: "localhost"
        USERS: wearefrank|pass_123|/home/wearefrank/dir|100000
      networks:
        - waf-net
      volumes:
        - ftp-v:/home/wearefrank/    
networks:
    waf-net:

volumes:
  samba-v:
  krb5kdc:  
  ftp-v:
